#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Auto-Start Programs
picom --config /home/kitroot/.config/picom/picom.conf --no-vsync &
polybar & 
xrandr --output Virtual-1 --mode 1920x1080
feh --bg-scale /home/kitroot/Pictures/bart-simpson-the-5120x2880-9398.png

